name: portfolio backend

on: 
  push: 
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: running simple script
        run: echo hello from portfolio backend
      - name: running npm
        run: npm install
      - name: run build
        run: npm build
    
    

